"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const authMiddleware_1 = require("../middleware/authMiddleware");
const upload_1 = require("../middleware/upload");
const academicServicesController_1 = require("../controllers/academicServicesController");
const router = (0, express_1.Router)();
router.get('/academic-services/availability', academicServicesController_1.getAcademicServicesAvailabilityPublic);
router.get('/student/academic-services/availability', authMiddleware_1.authenticate, (0, authMiddleware_1.requireRole)('STUDENT'), academicServicesController_1.getAcademicServicesAvailabilityStudent);
router.post('/student/academic-services', authMiddleware_1.authenticate, (0, authMiddleware_1.requireRole)('STUDENT'), academicServicesController_1.createAcademicServiceRequest);
router.get('/student/academic-services', authMiddleware_1.authenticate, (0, authMiddleware_1.requireRole)('STUDENT'), academicServicesController_1.getStudentAcademicServiceRequests);
router.post('/student/academic-services/:id/create-payment-order', authMiddleware_1.authenticate, (0, authMiddleware_1.requireRole)('STUDENT'), academicServicesController_1.createAcademicServicePaymentOrder);
router.post('/student/academic-services/:id/verify-payment', authMiddleware_1.authenticate, (0, authMiddleware_1.requireRole)('STUDENT'), academicServicesController_1.verifyAcademicServicePayment);
router.get('/admin/academic-services', authMiddleware_1.authenticate, (0, authMiddleware_1.requireRole)('ADMIN'), academicServicesController_1.getAllAcademicServiceRequests);
router.get('/admin/academic-services/settings', authMiddleware_1.authenticate, (0, authMiddleware_1.requireRole)('ADMIN'), academicServicesController_1.getAcademicServiceSettingsAdmin);
router.put('/admin/academic-services/settings', authMiddleware_1.authenticate, (0, authMiddleware_1.requireRole)('ADMIN'), academicServicesController_1.updateAcademicServiceSettingsAdmin);
router.put('/admin/academic-services/:id', authMiddleware_1.authenticate, (0, authMiddleware_1.requireRole)('ADMIN'), academicServicesController_1.updateAcademicServiceRequest);
router.post('/admin/academic-services/:id/attachments', authMiddleware_1.authenticate, (0, authMiddleware_1.requireRole)('ADMIN'), upload_1.academicServiceAttachmentUpload.array('files', 5), academicServicesController_1.uploadAcademicServiceAttachments);
exports.default = router;
